import Link from "next/link";
import type { Metadata } from "next";
import { siteConfig } from "@/lib/siteConfig";
import BrandMark from "@/components/BrandMark";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Terms of service for Pip beta, including AI coaching and usage policies.",
  alternates: { canonical: "/terms" },
};

export default function Terms() {
  return (
    <div className="min-h-screen bg-ground text-cream">
      <nav className="flex items-center px-6 py-3.5 border-b border-border">
        <Link href="/" className="flex items-center gap-2.5 no-underline text-cream">
          <BrandMark />
          <span className="font-extrabold text-lg tracking-tight">pip</span>
        </Link>
      </nav>

      <main className="max-w-[720px] mx-auto px-6 py-12">
        <h1 className="font-extrabold text-[32px] tracking-[-0.04em] mb-6">Terms of Service</h1>
        <p className="text-sm text-muted mb-2">Last updated: March 25, 2026</p>

        <div className="space-y-6 text-sm text-muted leading-relaxed">
          <section>
            <h2 className="font-bold text-lg text-cream mb-2">Agreement</h2>
            <p>By downloading, installing, or using Pip (&ldquo;the App&rdquo;), you agree to be bound by these Terms of Service. If you do not agree, do not use the App.</p>
          </section>

          <section>
            <h2 className="font-bold text-lg text-cream mb-2">Beta Software</h2>
            <p>Pip is currently in beta. The App is provided &ldquo;as is&rdquo; and may contain bugs, errors, or incomplete features. We make no guarantees about uptime, data persistence, or feature availability during the beta period.</p>
          </section>

          <section>
            <h2 className="font-bold text-lg text-cream mb-2">AI Coaching</h2>
            <p>Pip provides AI-powered coaching suggestions. These suggestions are generated by artificial intelligence and should not be considered professional advice. The coaching features are intended to help with task management and productivity — they are not a substitute for professional mental health, medical, or business advice.</p>
          </section>

          <section>
            <h2 className="font-bold text-lg text-cream mb-2">Your Content</h2>
            <p>You retain ownership of all content you create in Pip, including tasks, notes, and sprint data. We do not claim any intellectual property rights over your content.</p>
          </section>

          <section>
            <h2 className="font-bold text-lg text-cream mb-2">Acceptable Use</h2>
            <p>You agree not to misuse the App or its AI features. This includes attempting to extract, reverse-engineer, or manipulate the AI systems, or using the App for any unlawful purpose.</p>
          </section>

          <section>
            <h2 className="font-bold text-lg text-cream mb-2">Service Availability</h2>
            <p>We strive to keep Pip available but cannot guarantee uninterrupted access. We may modify, suspend, or discontinue any part of the service at any time without notice. Core features that work offline (voice transcription, local task management) will continue to function without an internet connection.</p>
          </section>

          <section>
            <h2 className="font-bold text-lg text-cream mb-2">Limitation of Liability</h2>
            <p>To the maximum extent permitted by law, Resoworks shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses resulting from your use of the App.</p>
          </section>

          <section>
            <h2 className="font-bold text-lg text-cream mb-2">Changes to Terms</h2>
            <p>We reserve the right to modify these terms at any time. We will provide notice of significant changes through the App or by updating this page. Continued use of the App after changes constitutes acceptance of the new terms.</p>
          </section>

          <section>
            <h2 className="font-bold text-lg text-cream mb-2">Contact</h2>
            <p>
              For questions about these terms, contact us at{" "}
              <a href={`mailto:${siteConfig.legalEmail}`} className="text-cream hover:text-mint-sub">
                {siteConfig.legalEmail}
              </a>
              .
            </p>
          </section>
        </div>
      </main>

      <footer className="text-center px-6 py-6 border-t border-border text-xs text-[#666]">
        <div>&copy; Resoworks, 2026 · <Link href="/privacy" className="text-[#666] no-underline hover:text-muted">Privacy Policy</Link> · <Link href="/terms" className="text-[#666] no-underline hover:text-muted">Terms of Service</Link></div>
      </footer>
    </div>
  );
}
